//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.24 at 10:22:41 AM IST 
//


package ipd.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IPDConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPDConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ipdGeneralConfig" type="{http://www.cdacnoida.in/his/IpdConfig}IPDGeneralConfigType"/>
 *         &lt;element name="ipdPassDetails" type="{http://www.cdacnoida.in/his/IpdConfig}IPDPassDetails"/>
 *         &lt;element name="ipdReportDetails" type="{http://www.cdacnoida.in/his/IpdConfig}IPDReportDetails"/>
 *         &lt;element name="ipdBillDetails" type="{http://www.cdacnoida.in/his/IpdConfig}IPDBillDetails"/>
 *         &lt;element name="ipdPrintDetails" type="{http://www.cdacnoida.in/his/IpdConfig}IPDPrintConfigType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPDConfig", propOrder = {
    "ipdGeneralConfig",
    "ipdPassDetails",
    "ipdReportDetails",
    "ipdBillDetails",
    "ipdPrintDetails"
})
public class IPDConfig {

    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected IPDGeneralConfigType ipdGeneralConfig;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected IPDPassDetails ipdPassDetails;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected IPDReportDetails ipdReportDetails;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected IPDBillDetails ipdBillDetails;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected IPDPrintConfigType ipdPrintDetails;

    /**
     * Gets the value of the ipdGeneralConfig property.
     * 
     * @return
     *     possible object is
     *     {@link IPDGeneralConfigType }
     *     
     */
    public IPDGeneralConfigType getIpdGeneralConfig() {
        return ipdGeneralConfig;
    }

    /**
     * Sets the value of the ipdGeneralConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPDGeneralConfigType }
     *     
     */
    public void setIpdGeneralConfig(IPDGeneralConfigType value) {
        this.ipdGeneralConfig = value;
    }

    /**
     * Gets the value of the ipdPassDetails property.
     * 
     * @return
     *     possible object is
     *     {@link IPDPassDetails }
     *     
     */
    public IPDPassDetails getIpdPassDetails() {
        return ipdPassDetails;
    }

    /**
     * Sets the value of the ipdPassDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPDPassDetails }
     *     
     */
    public void setIpdPassDetails(IPDPassDetails value) {
        this.ipdPassDetails = value;
    }

    /**
     * Gets the value of the ipdReportDetails property.
     * 
     * @return
     *     possible object is
     *     {@link IPDReportDetails }
     *     
     */
    public IPDReportDetails getIpdReportDetails() {
        return ipdReportDetails;
    }

    /**
     * Sets the value of the ipdReportDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPDReportDetails }
     *     
     */
    public void setIpdReportDetails(IPDReportDetails value) {
        this.ipdReportDetails = value;
    }

    /**
     * Gets the value of the ipdBillDetails property.
     * 
     * @return
     *     possible object is
     *     {@link IPDBillDetails }
     *     
     */
    public IPDBillDetails getIpdBillDetails() {
        return ipdBillDetails;
    }

    /**
     * Sets the value of the ipdBillDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPDBillDetails }
     *     
     */
    public void setIpdBillDetails(IPDBillDetails value) {
        this.ipdBillDetails = value;
    }

    /**
     * Gets the value of the ipdPrintDetails property.
     * 
     * @return
     *     possible object is
     *     {@link IPDPrintConfigType }
     *     
     */
    public IPDPrintConfigType getIpdPrintDetails() {
        return ipdPrintDetails;
    }

    /**
     * Sets the value of the ipdPrintDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPDPrintConfigType }
     *     
     */
    public void setIpdPrintDetails(IPDPrintConfigType value) {
        this.ipdPrintDetails = value;
    }

}
