//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.24 at 10:22:41 AM IST 
//


package ipd.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IPDPassDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPDPassDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="noOfFreePass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noOfPaidPass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="newFreePassValidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="newPaidPassValidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="renewFreePassValidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="renewPaidPassValidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="summerMorningFromTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="summerMorningToTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="summerEveningFromTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="summerEveningToTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="winterMorningFromTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="winterMorningToTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="winterEveningFromTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="winterEveningToTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="printRequest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noOfFreePassAtTimeOfAdmission" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paidPassCharges" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paidPassRenewCharges" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="passReprintCharges" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attendentPassRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attendentPassGenerateAtAdmissionTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPDPassDetails", propOrder = {
    "noOfFreePass",
    "noOfPaidPass",
    "newFreePassValidity",
    "newPaidPassValidity",
    "renewFreePassValidity",
    "renewPaidPassValidity",
    "summerMorningFromTime",
    "summerMorningToTime",
    "summerEveningFromTime",
    "summerEveningToTime",
    "winterMorningFromTime",
    "winterMorningToTime",
    "winterEveningFromTime",
    "winterEveningToTime",
    "printRequest",
    "noOfFreePassAtTimeOfAdmission",
    "paidPassCharges",
    "paidPassRenewCharges",
    "passReprintCharges",
    "attendentPassRequired",
    "attendentPassGenerateAtAdmissionTime"
})
public class IPDPassDetails {

    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String noOfFreePass;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String noOfPaidPass;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String newFreePassValidity;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String newPaidPassValidity;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String renewFreePassValidity;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String renewPaidPassValidity;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String summerMorningFromTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String summerMorningToTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String summerEveningFromTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String summerEveningToTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String winterMorningFromTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String winterMorningToTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String winterEveningFromTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String winterEveningToTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String printRequest;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String noOfFreePassAtTimeOfAdmission;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String paidPassCharges;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String paidPassRenewCharges;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String passReprintCharges;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String attendentPassRequired;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String attendentPassGenerateAtAdmissionTime;

    /**
     * Gets the value of the noOfFreePass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfFreePass() {
        return noOfFreePass;
    }

    /**
     * Sets the value of the noOfFreePass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfFreePass(String value) {
        this.noOfFreePass = value;
    }

    /**
     * Gets the value of the noOfPaidPass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfPaidPass() {
        return noOfPaidPass;
    }

    /**
     * Sets the value of the noOfPaidPass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfPaidPass(String value) {
        this.noOfPaidPass = value;
    }

    /**
     * Gets the value of the newFreePassValidity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewFreePassValidity() {
        return newFreePassValidity;
    }

    /**
     * Sets the value of the newFreePassValidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewFreePassValidity(String value) {
        this.newFreePassValidity = value;
    }

    /**
     * Gets the value of the newPaidPassValidity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewPaidPassValidity() {
        return newPaidPassValidity;
    }

    /**
     * Sets the value of the newPaidPassValidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewPaidPassValidity(String value) {
        this.newPaidPassValidity = value;
    }

    /**
     * Gets the value of the renewFreePassValidity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenewFreePassValidity() {
        return renewFreePassValidity;
    }

    /**
     * Sets the value of the renewFreePassValidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenewFreePassValidity(String value) {
        this.renewFreePassValidity = value;
    }

    /**
     * Gets the value of the renewPaidPassValidity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenewPaidPassValidity() {
        return renewPaidPassValidity;
    }

    /**
     * Sets the value of the renewPaidPassValidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenewPaidPassValidity(String value) {
        this.renewPaidPassValidity = value;
    }

    /**
     * Gets the value of the summerMorningFromTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummerMorningFromTime() {
        return summerMorningFromTime;
    }

    /**
     * Sets the value of the summerMorningFromTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummerMorningFromTime(String value) {
        this.summerMorningFromTime = value;
    }

    /**
     * Gets the value of the summerMorningToTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummerMorningToTime() {
        return summerMorningToTime;
    }

    /**
     * Sets the value of the summerMorningToTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummerMorningToTime(String value) {
        this.summerMorningToTime = value;
    }

    /**
     * Gets the value of the summerEveningFromTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummerEveningFromTime() {
        return summerEveningFromTime;
    }

    /**
     * Sets the value of the summerEveningFromTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummerEveningFromTime(String value) {
        this.summerEveningFromTime = value;
    }

    /**
     * Gets the value of the summerEveningToTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummerEveningToTime() {
        return summerEveningToTime;
    }

    /**
     * Sets the value of the summerEveningToTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummerEveningToTime(String value) {
        this.summerEveningToTime = value;
    }

    /**
     * Gets the value of the winterMorningFromTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWinterMorningFromTime() {
        return winterMorningFromTime;
    }

    /**
     * Sets the value of the winterMorningFromTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWinterMorningFromTime(String value) {
        this.winterMorningFromTime = value;
    }

    /**
     * Gets the value of the winterMorningToTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWinterMorningToTime() {
        return winterMorningToTime;
    }

    /**
     * Sets the value of the winterMorningToTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWinterMorningToTime(String value) {
        this.winterMorningToTime = value;
    }

    /**
     * Gets the value of the winterEveningFromTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWinterEveningFromTime() {
        return winterEveningFromTime;
    }

    /**
     * Sets the value of the winterEveningFromTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWinterEveningFromTime(String value) {
        this.winterEveningFromTime = value;
    }

    /**
     * Gets the value of the winterEveningToTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWinterEveningToTime() {
        return winterEveningToTime;
    }

    /**
     * Sets the value of the winterEveningToTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWinterEveningToTime(String value) {
        this.winterEveningToTime = value;
    }

    /**
     * Gets the value of the printRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintRequest() {
        return printRequest;
    }

    /**
     * Sets the value of the printRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintRequest(String value) {
        this.printRequest = value;
    }

    /**
     * Gets the value of the noOfFreePassAtTimeOfAdmission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfFreePassAtTimeOfAdmission() {
        return noOfFreePassAtTimeOfAdmission;
    }

    /**
     * Sets the value of the noOfFreePassAtTimeOfAdmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfFreePassAtTimeOfAdmission(String value) {
        this.noOfFreePassAtTimeOfAdmission = value;
    }

    /**
     * Gets the value of the paidPassCharges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaidPassCharges() {
        return paidPassCharges;
    }

    /**
     * Sets the value of the paidPassCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaidPassCharges(String value) {
        this.paidPassCharges = value;
    }

    /**
     * Gets the value of the paidPassRenewCharges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaidPassRenewCharges() {
        return paidPassRenewCharges;
    }

    /**
     * Sets the value of the paidPassRenewCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaidPassRenewCharges(String value) {
        this.paidPassRenewCharges = value;
    }

    /**
     * Gets the value of the passReprintCharges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassReprintCharges() {
        return passReprintCharges;
    }

    /**
     * Sets the value of the passReprintCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassReprintCharges(String value) {
        this.passReprintCharges = value;
    }

    /**
     * Gets the value of the attendentPassRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttendentPassRequired() {
        return attendentPassRequired;
    }

    /**
     * Sets the value of the attendentPassRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttendentPassRequired(String value) {
        this.attendentPassRequired = value;
    }

    /**
     * Gets the value of the attendentPassGenerateAtAdmissionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttendentPassGenerateAtAdmissionTime() {
        return attendentPassGenerateAtAdmissionTime;
    }

    /**
     * Sets the value of the attendentPassGenerateAtAdmissionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttendentPassGenerateAtAdmissionTime(String value) {
        this.attendentPassGenerateAtAdmissionTime = value;
    }

}
