//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.24 at 10:22:41 AM IST 
//


package ipd.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IPDPrintConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPDPrintConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="noOfLinesAdmission" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noOfLineNewBornBay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noOfLinesVisitorPass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPDPrintConfigType", propOrder = {
    "noOfLinesAdmission",
    "noOfLineNewBornBay",
    "noOfLinesVisitorPass"
})
public class IPDPrintConfigType {

    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String noOfLinesAdmission;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String noOfLineNewBornBay;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String noOfLinesVisitorPass;

    /**
     * Gets the value of the noOfLinesAdmission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfLinesAdmission() {
        return noOfLinesAdmission;
    }

    /**
     * Sets the value of the noOfLinesAdmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfLinesAdmission(String value) {
        this.noOfLinesAdmission = value;
    }

    /**
     * Gets the value of the noOfLineNewBornBay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfLineNewBornBay() {
        return noOfLineNewBornBay;
    }

    /**
     * Sets the value of the noOfLineNewBornBay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfLineNewBornBay(String value) {
        this.noOfLineNewBornBay = value;
    }

    /**
     * Gets the value of the noOfLinesVisitorPass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfLinesVisitorPass() {
        return noOfLinesVisitorPass;
    }

    /**
     * Sets the value of the noOfLinesVisitorPass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfLinesVisitorPass(String value) {
        this.noOfLinesVisitorPass = value;
    }

}
