//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.24 at 10:22:41 AM IST 
//


package ipd.setup;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ipd.setup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IpdConfig_QNAME = new QName("http://www.cdacnoida.in/his/IpdConfig", "ipdConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ipd.setup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenWardApprovalType }
     * 
     */
    public GenWardApprovalType createGenWardApprovalType() {
        return new GenWardApprovalType();
    }

    /**
     * Create an instance of {@link PrivateWardApprovalType }
     * 
     */
    public PrivateWardApprovalType createPrivateWardApprovalType() {
        return new PrivateWardApprovalType();
    }

    /**
     * Create an instance of {@link IPDConfig }
     * 
     */
    public IPDConfig createIPDConfig() {
        return new IPDConfig();
    }

    /**
     * Create an instance of {@link IPDBillDetails }
     * 
     */
    public IPDBillDetails createIPDBillDetails() {
        return new IPDBillDetails();
    }

    /**
     * Create an instance of {@link IPDPassDetails }
     * 
     */
    public IPDPassDetails createIPDPassDetails() {
        return new IPDPassDetails();
    }

    /**
     * Create an instance of {@link IPDGeneralConfigType }
     * 
     */
    public IPDGeneralConfigType createIPDGeneralConfigType() {
        return new IPDGeneralConfigType();
    }

    /**
     * Create an instance of {@link IPDPrintConfigType }
     * 
     */
    public IPDPrintConfigType createIPDPrintConfigType() {
        return new IPDPrintConfigType();
    }

    /**
     * Create an instance of {@link IPDReportDetails }
     * 
     */
    public IPDReportDetails createIPDReportDetails() {
        return new IPDReportDetails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IPDConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cdacnoida.in/his/IpdConfig", name = "ipdConfig")
    public JAXBElement<IPDConfig> createIpdConfig(IPDConfig value) {
        return new JAXBElement<IPDConfig>(_IpdConfig_QNAME, IPDConfig.class, null, value);
    }

}
