//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.24 at 10:22:41 AM IST 
//


package ipd.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IPDGeneralConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPDGeneralConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="genWardAdmission" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="genWardApproval" type="{http://www.cdacnoida.in/his/IpdConfig}GenWardApprovalType"/>
 *         &lt;element name="privateWardAdmission" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="privateWardApproval" type="{http://www.cdacnoida.in/his/IpdConfig}PrivateWardApprovalType"/>
 *         &lt;element name="bookBed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billing" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="negativeBilling" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="patientCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="govtEmpBasicPayLimit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pvtEmpMonIncomeLimit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="admissionAdviceValidityFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="admissionChargeTakenAtAdmissionCounter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="newBornBabyRegistrationCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="newBornBabyAdmissionCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="admissionAdviceValidityTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modificationTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dischargeCancellationTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="advanceAmountTakenFromNewBornBaby" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="blockBedExpiryTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="admissionReprintCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dischargeReprintCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noOfLineAmissionSlip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noOfLineVisitorPassSlip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="admissionProcessOnline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="privateWardType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="icuWardType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="daysForPurgingRecordFromCurrentlyAdmissionDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="purgeTimeForNotReported" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="msApprovalFormNoRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dischargeProcessType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="newBornBabyProcess" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="minAgeToBeMother" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maxNoOfBabyMotherCanBorn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notReportedLeaveHours" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="diagnosisType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="admissionAdviceMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="belongingRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issueItemRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nurseChecklistMandatory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPDGeneralConfigType", propOrder = {
    "genWardAdmission",
    "genWardApproval",
    "privateWardAdmission",
    "privateWardApproval",
    "bookBed",
    "billing",
    "negativeBilling",
    "patientCategory",
    "govtEmpBasicPayLimit",
    "pvtEmpMonIncomeLimit",
    "admissionAdviceValidityFrom",
    "admissionChargeTakenAtAdmissionCounter",
    "newBornBabyRegistrationCharge",
    "newBornBabyAdmissionCharge",
    "admissionAdviceValidityTo",
    "modificationTime",
    "dischargeCancellationTime",
    "advanceAmountTakenFromNewBornBaby",
    "blockBedExpiryTime",
    "admissionReprintCharge",
    "dischargeReprintCharge",
    "noOfLineAmissionSlip",
    "noOfLineVisitorPassSlip",
    "admissionProcessOnline",
    "privateWardType",
    "icuWardType",
    "daysForPurgingRecordFromCurrentlyAdmissionDetails",
    "purgeTimeForNotReported",
    "msApprovalFormNoRequired",
    "dischargeProcessType",
    "newBornBabyProcess",
    "minAgeToBeMother",
    "maxNoOfBabyMotherCanBorn",
    "notReportedLeaveHours",
    "diagnosisType",
    "admissionAdviceMode",
    "belongingRequired",
    "issueItemRequired",
    "nurseChecklistMandatory"
})
public class IPDGeneralConfigType {

    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String genWardAdmission;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected GenWardApprovalType genWardApproval;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String privateWardAdmission;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected PrivateWardApprovalType privateWardApproval;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String bookBed;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String billing;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String negativeBilling;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String patientCategory;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String govtEmpBasicPayLimit;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String pvtEmpMonIncomeLimit;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String admissionAdviceValidityFrom;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String admissionChargeTakenAtAdmissionCounter;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String newBornBabyRegistrationCharge;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String newBornBabyAdmissionCharge;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String admissionAdviceValidityTo;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String modificationTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String dischargeCancellationTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String advanceAmountTakenFromNewBornBaby;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String blockBedExpiryTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String admissionReprintCharge;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String dischargeReprintCharge;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String noOfLineAmissionSlip;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String noOfLineVisitorPassSlip;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String admissionProcessOnline;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String privateWardType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String icuWardType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String daysForPurgingRecordFromCurrentlyAdmissionDetails;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String purgeTimeForNotReported;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String msApprovalFormNoRequired;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String dischargeProcessType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String newBornBabyProcess;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String minAgeToBeMother;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String maxNoOfBabyMotherCanBorn;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String notReportedLeaveHours;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String diagnosisType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String admissionAdviceMode;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String belongingRequired;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String issueItemRequired;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/IpdConfig", required = true)
    protected String nurseChecklistMandatory;

    /**
     * Gets the value of the genWardAdmission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenWardAdmission() {
        return genWardAdmission;
    }

    /**
     * Sets the value of the genWardAdmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenWardAdmission(String value) {
        this.genWardAdmission = value;
    }

    /**
     * Gets the value of the genWardApproval property.
     * 
     * @return
     *     possible object is
     *     {@link GenWardApprovalType }
     *     
     */
    public GenWardApprovalType getGenWardApproval() {
        return genWardApproval;
    }

    /**
     * Sets the value of the genWardApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenWardApprovalType }
     *     
     */
    public void setGenWardApproval(GenWardApprovalType value) {
        this.genWardApproval = value;
    }

    /**
     * Gets the value of the privateWardAdmission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateWardAdmission() {
        return privateWardAdmission;
    }

    /**
     * Sets the value of the privateWardAdmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateWardAdmission(String value) {
        this.privateWardAdmission = value;
    }

    /**
     * Gets the value of the privateWardApproval property.
     * 
     * @return
     *     possible object is
     *     {@link PrivateWardApprovalType }
     *     
     */
    public PrivateWardApprovalType getPrivateWardApproval() {
        return privateWardApproval;
    }

    /**
     * Sets the value of the privateWardApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivateWardApprovalType }
     *     
     */
    public void setPrivateWardApproval(PrivateWardApprovalType value) {
        this.privateWardApproval = value;
    }

    /**
     * Gets the value of the bookBed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookBed() {
        return bookBed;
    }

    /**
     * Sets the value of the bookBed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookBed(String value) {
        this.bookBed = value;
    }

    /**
     * Gets the value of the billing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBilling() {
        return billing;
    }

    /**
     * Sets the value of the billing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBilling(String value) {
        this.billing = value;
    }

    /**
     * Gets the value of the negativeBilling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNegativeBilling() {
        return negativeBilling;
    }

    /**
     * Sets the value of the negativeBilling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNegativeBilling(String value) {
        this.negativeBilling = value;
    }

    /**
     * Gets the value of the patientCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientCategory() {
        return patientCategory;
    }

    /**
     * Sets the value of the patientCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientCategory(String value) {
        this.patientCategory = value;
    }

    /**
     * Gets the value of the govtEmpBasicPayLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGovtEmpBasicPayLimit() {
        return govtEmpBasicPayLimit;
    }

    /**
     * Sets the value of the govtEmpBasicPayLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGovtEmpBasicPayLimit(String value) {
        this.govtEmpBasicPayLimit = value;
    }

    /**
     * Gets the value of the pvtEmpMonIncomeLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPvtEmpMonIncomeLimit() {
        return pvtEmpMonIncomeLimit;
    }

    /**
     * Sets the value of the pvtEmpMonIncomeLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPvtEmpMonIncomeLimit(String value) {
        this.pvtEmpMonIncomeLimit = value;
    }

    /**
     * Gets the value of the admissionAdviceValidityFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmissionAdviceValidityFrom() {
        return admissionAdviceValidityFrom;
    }

    /**
     * Sets the value of the admissionAdviceValidityFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmissionAdviceValidityFrom(String value) {
        this.admissionAdviceValidityFrom = value;
    }

    /**
     * Gets the value of the admissionChargeTakenAtAdmissionCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmissionChargeTakenAtAdmissionCounter() {
        return admissionChargeTakenAtAdmissionCounter;
    }

    /**
     * Sets the value of the admissionChargeTakenAtAdmissionCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmissionChargeTakenAtAdmissionCounter(String value) {
        this.admissionChargeTakenAtAdmissionCounter = value;
    }

    /**
     * Gets the value of the newBornBabyRegistrationCharge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewBornBabyRegistrationCharge() {
        return newBornBabyRegistrationCharge;
    }

    /**
     * Sets the value of the newBornBabyRegistrationCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewBornBabyRegistrationCharge(String value) {
        this.newBornBabyRegistrationCharge = value;
    }

    /**
     * Gets the value of the newBornBabyAdmissionCharge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewBornBabyAdmissionCharge() {
        return newBornBabyAdmissionCharge;
    }

    /**
     * Sets the value of the newBornBabyAdmissionCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewBornBabyAdmissionCharge(String value) {
        this.newBornBabyAdmissionCharge = value;
    }

    /**
     * Gets the value of the admissionAdviceValidityTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmissionAdviceValidityTo() {
        return admissionAdviceValidityTo;
    }

    /**
     * Sets the value of the admissionAdviceValidityTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmissionAdviceValidityTo(String value) {
        this.admissionAdviceValidityTo = value;
    }

    /**
     * Gets the value of the modificationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationTime() {
        return modificationTime;
    }

    /**
     * Sets the value of the modificationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationTime(String value) {
        this.modificationTime = value;
    }

    /**
     * Gets the value of the dischargeCancellationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDischargeCancellationTime() {
        return dischargeCancellationTime;
    }

    /**
     * Sets the value of the dischargeCancellationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDischargeCancellationTime(String value) {
        this.dischargeCancellationTime = value;
    }

    /**
     * Gets the value of the advanceAmountTakenFromNewBornBaby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvanceAmountTakenFromNewBornBaby() {
        return advanceAmountTakenFromNewBornBaby;
    }

    /**
     * Sets the value of the advanceAmountTakenFromNewBornBaby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvanceAmountTakenFromNewBornBaby(String value) {
        this.advanceAmountTakenFromNewBornBaby = value;
    }

    /**
     * Gets the value of the blockBedExpiryTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockBedExpiryTime() {
        return blockBedExpiryTime;
    }

    /**
     * Sets the value of the blockBedExpiryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockBedExpiryTime(String value) {
        this.blockBedExpiryTime = value;
    }

    /**
     * Gets the value of the admissionReprintCharge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmissionReprintCharge() {
        return admissionReprintCharge;
    }

    /**
     * Sets the value of the admissionReprintCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmissionReprintCharge(String value) {
        this.admissionReprintCharge = value;
    }

    /**
     * Gets the value of the dischargeReprintCharge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDischargeReprintCharge() {
        return dischargeReprintCharge;
    }

    /**
     * Sets the value of the dischargeReprintCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDischargeReprintCharge(String value) {
        this.dischargeReprintCharge = value;
    }

    /**
     * Gets the value of the noOfLineAmissionSlip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfLineAmissionSlip() {
        return noOfLineAmissionSlip;
    }

    /**
     * Sets the value of the noOfLineAmissionSlip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfLineAmissionSlip(String value) {
        this.noOfLineAmissionSlip = value;
    }

    /**
     * Gets the value of the noOfLineVisitorPassSlip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfLineVisitorPassSlip() {
        return noOfLineVisitorPassSlip;
    }

    /**
     * Sets the value of the noOfLineVisitorPassSlip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfLineVisitorPassSlip(String value) {
        this.noOfLineVisitorPassSlip = value;
    }

    /**
     * Gets the value of the admissionProcessOnline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmissionProcessOnline() {
        return admissionProcessOnline;
    }

    /**
     * Sets the value of the admissionProcessOnline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmissionProcessOnline(String value) {
        this.admissionProcessOnline = value;
    }

    /**
     * Gets the value of the privateWardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateWardType() {
        return privateWardType;
    }

    /**
     * Sets the value of the privateWardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateWardType(String value) {
        this.privateWardType = value;
    }

    /**
     * Gets the value of the icuWardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcuWardType() {
        return icuWardType;
    }

    /**
     * Sets the value of the icuWardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcuWardType(String value) {
        this.icuWardType = value;
    }

    /**
     * Gets the value of the daysForPurgingRecordFromCurrentlyAdmissionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaysForPurgingRecordFromCurrentlyAdmissionDetails() {
        return daysForPurgingRecordFromCurrentlyAdmissionDetails;
    }

    /**
     * Sets the value of the daysForPurgingRecordFromCurrentlyAdmissionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaysForPurgingRecordFromCurrentlyAdmissionDetails(String value) {
        this.daysForPurgingRecordFromCurrentlyAdmissionDetails = value;
    }

    /**
     * Gets the value of the purgeTimeForNotReported property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurgeTimeForNotReported() {
        return purgeTimeForNotReported;
    }

    /**
     * Sets the value of the purgeTimeForNotReported property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurgeTimeForNotReported(String value) {
        this.purgeTimeForNotReported = value;
    }

    /**
     * Gets the value of the msApprovalFormNoRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsApprovalFormNoRequired() {
        return msApprovalFormNoRequired;
    }

    /**
     * Sets the value of the msApprovalFormNoRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsApprovalFormNoRequired(String value) {
        this.msApprovalFormNoRequired = value;
    }

    /**
     * Gets the value of the dischargeProcessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDischargeProcessType() {
        return dischargeProcessType;
    }

    /**
     * Sets the value of the dischargeProcessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDischargeProcessType(String value) {
        this.dischargeProcessType = value;
    }

    /**
     * Gets the value of the newBornBabyProcess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewBornBabyProcess() {
        return newBornBabyProcess;
    }

    /**
     * Sets the value of the newBornBabyProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewBornBabyProcess(String value) {
        this.newBornBabyProcess = value;
    }

    /**
     * Gets the value of the minAgeToBeMother property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinAgeToBeMother() {
        return minAgeToBeMother;
    }

    /**
     * Sets the value of the minAgeToBeMother property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinAgeToBeMother(String value) {
        this.minAgeToBeMother = value;
    }

    /**
     * Gets the value of the maxNoOfBabyMotherCanBorn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxNoOfBabyMotherCanBorn() {
        return maxNoOfBabyMotherCanBorn;
    }

    /**
     * Sets the value of the maxNoOfBabyMotherCanBorn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxNoOfBabyMotherCanBorn(String value) {
        this.maxNoOfBabyMotherCanBorn = value;
    }

    /**
     * Gets the value of the notReportedLeaveHours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotReportedLeaveHours() {
        return notReportedLeaveHours;
    }

    /**
     * Sets the value of the notReportedLeaveHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotReportedLeaveHours(String value) {
        this.notReportedLeaveHours = value;
    }

    /**
     * Gets the value of the diagnosisType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosisType() {
        return diagnosisType;
    }

    /**
     * Sets the value of the diagnosisType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosisType(String value) {
        this.diagnosisType = value;
    }

    /**
     * Gets the value of the admissionAdviceMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmissionAdviceMode() {
        return admissionAdviceMode;
    }

    /**
     * Sets the value of the admissionAdviceMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmissionAdviceMode(String value) {
        this.admissionAdviceMode = value;
    }

    /**
     * Gets the value of the belongingRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBelongingRequired() {
        return belongingRequired;
    }

    /**
     * Sets the value of the belongingRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBelongingRequired(String value) {
        this.belongingRequired = value;
    }

    /**
     * Gets the value of the issueItemRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueItemRequired() {
        return issueItemRequired;
    }

    /**
     * Sets the value of the issueItemRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueItemRequired(String value) {
        this.issueItemRequired = value;
    }

    /**
     * Gets the value of the nurseChecklistMandatory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNurseChecklistMandatory() {
        return nurseChecklistMandatory;
    }

    /**
     * Sets the value of the nurseChecklistMandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNurseChecklistMandatory(String value) {
        this.nurseChecklistMandatory = value;
    }

}
